steps:
- name: 'gcr.io/kaniko-project/executor:latest'
    args:
    - --destination=gcr.io/$PROJECT_ID/image
    - --cache=true
    - --cache-ttl=24h
- name: node
    entrypoint: npm
    args: ['install']
- name: node
    entrypoint: npm
    args: ['test']
    timeout: 20s